// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"iyyzh-kratos/internal/biz"
	"iyyzh-kratos/internal/conf"
	"iyyzh-kratos/internal/data"
	"iyyzh-kratos/internal/server"
	"iyyzh-kratos/internal/service"
)

// Injectors from wire.go:

//使用 Makefile 编写的命令 make wire 命令生成编译期依赖注入代码 wire_gen.go
//wireApp 初始化模块 依赖注入的入口
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	orderRepo := data.NewOrderRepo(dataData, logger)
	orderUseCase := biz.NewOrderUseCase(orderRepo, logger)
	realwordService := service.NewRealwordService(userUseCase, orderUseCase)
	grpcServer := server.NewGRPCServer(confServer, realwordService, logger)
	httpServer := server.NewHTTPServer(confServer, realwordService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
